-- 0015_create_webhooks.sql
-- Outbound webhooks: per-organization subscriptions, and a log of what was delivered.
-- Strictly additive and idempotent (CREATE ... IF NOT EXISTS), so re-running is a no-op and
-- no prior-phase column is altered or dropped.
--
-- The platform could observe everything and tell nobody: a budget threshold, a guardrail
-- block, and a finished run were all visible only to somebody who went looking. These two
-- tables are the seam that lets the platform speak first.
CREATE TABLE IF NOT EXISTS webhook_subscriptions (
    id          UUID PRIMARY KEY,
    org_id      UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    -- The destination. Admitted by `webhooks/security.py` before the write (https only
    -- outside local development, no credentials in the URL, and never an address that
    -- resolves inside the deployment's own network), and re-validated at delivery time.
    url         TEXT NOT NULL,
    -- The HMAC signing key, base64url, generated by the server.
    --
    -- Stored in a RECOVERABLE form, unlike `api_keys.secret_hash`, and the asymmetry is
    -- deliberate rather than an oversight: an API key is only ever *verified*, so a hash is
    -- sufficient, while a webhook secret must be *used* to sign every outgoing request, and
    -- a hash cannot sign. This is what Stripe and GitHub do for the same reason. It is
    -- returned to the caller exactly once, at creation, and no read path in the application
    -- can ever produce it again (see docs/KNOWN_LIMITATIONS.md).
    secret      TEXT NOT NULL,
    -- The subscribed event names, from the closed vocabulary in `webhooks/base.py`. TEXT[]
    -- rather than a join table: the list is short, always read whole, and never queried by
    -- element from the API — and it makes "which subscriptions want this event" one scan.
    events      TEXT[] NOT NULL,
    description TEXT,
    -- A paused subscription is kept, not deleted: pausing a noisy endpoint while it is fixed
    -- must not destroy the secret its consumer is already verifying against.
    active      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The only read pattern: one org's subscriptions, oldest first (a stable list order for the
-- console), plus the emitter's "who wants this event" lookup, which is the same scan.
CREATE INDEX IF NOT EXISTS webhook_subscriptions_org_idx
    ON webhook_subscriptions (org_id, created_at);

-- One row per (event, subscription) delivery attempt SEQUENCE — not per HTTP attempt. What
-- an operator debugging a broken consumer needs is "did event X reach endpoint Y, and if
-- not, why"; the retry count is a field on that answer rather than three rows to correlate.
CREATE TABLE IF NOT EXISTS webhook_deliveries (
    id              UUID PRIMARY KEY,
    org_id          UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    -- CASCADE: a delivery log entry describes a subscription and is meaningless without it.
    -- Deleting a subscription therefore deletes its log, which is also the tenant's only way
    -- to remove that history.
    subscription_id UUID NOT NULL
                    REFERENCES webhook_subscriptions(id) ON DELETE CASCADE,
    event           TEXT NOT NULL,
    -- 'delivered' = the endpoint answered 2xx. 'failed' = every attempt was exhausted.
    -- A CHECK rather than an enum type so adding a status stays an application change.
    status          TEXT NOT NULL CHECK (status IN ('delivered', 'failed')),
    attempts        INTEGER NOT NULL CHECK (attempts >= 1),
    -- The last HTTP status seen, or NULL when no response was ever obtained (DNS failure,
    -- connection refused, timeout) — which is itself the useful distinction.
    response_status INTEGER,
    -- A short, sanitised failure summary. Never the response body: that body comes from
    -- outside the trust boundary and this column is read by the tenant's admins.
    error           TEXT,
    -- Time spent in HTTP work only, excluding the backoff sleeps between attempts, so the
    -- number answers "how slow is this endpoint" rather than "how many times did we retry".
    duration_ms     INTEGER NOT NULL CHECK (duration_ms >= 0),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The only read pattern: one subscription's deliveries, newest first, keyset-paginated.
-- `id DESC` breaks ties so a page boundary cannot repeat or skip a row when several
-- deliveries share a timestamp (a fan-out writes several in the same millisecond).
CREATE INDEX IF NOT EXISTS webhook_deliveries_sub_time_idx
    ON webhook_deliveries (subscription_id, created_at DESC, id DESC);
