/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/agent/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Agent
         * @description Run the bounded agent loop and return its grounded result (Req 1.7, 8.5).
         *
         *     The input guardrail pipeline runs **before** the orchestrator is invoked: a blocking
         *     guardrail raises ``AppError("guardrail_blocked", 400)`` and the agent loop is never
         *     reached (Req 5.4). The output pipeline runs on the final answer and its flags are
         *     attached to the response without blocking (Req 5.5, 5.6).
         */
        post: operations["run_agent_agent_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/runs/{run_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Trace
         * @description Return the ordered trace for the caller's org run; 404 when unknown/cross-tenant (Req 10.3, 4.3).
         */
        get: operations["get_run_trace_agent_runs__run_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream Agent
         * @description Stream the agent run over Server-Sent Events, scoped to the caller's org (Req 9.1-9.9).
         */
        post: operations["stream_agent_agent_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Usage
         * @description Return the usage report for the caller's org over ``[start, end]`` (Req 3.1, 3.4).
         *
         *     ``start`` defaults to the epoch and ``end`` to now, so an unbounded query returns the
         *     org's entire history. The report is scoped to ``principal.org_id`` at the data-access
         *     layer, so no other tenant's usage can contribute (Req 3.3, 10.5).
         */
        get: operations["get_usage_analytics_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Verify credentials and return a bearer Access_Token (Req 1.2, 1.3).
         *
         *     An unknown email or a password mismatch raises ``AppError("auth_failed", 401)``.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Re-issue a token from a still-valid, non-expired bearer token (Req 1.5).
         *
         *     An absent, malformed, wrong-secret, or expired token yields 401 — the same uniform
         *     ``unauthorized`` envelope produced by the Principal_Dependency.
         */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register-self": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register Self
         * @description Create an Organization + owner User and return an Access_Token (Req 1.1, 1.2).
         *
         *     Validates password strength and email uniqueness first; the duplicate-email branch
         *     returns before any hash is computed.
         */
        post: operations["register_self_auth_register_self_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Conversation
         * @description Create a conversation owned by the caller's org (Req 8.1, 4.4).
         */
        post: operations["create_conversation_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation
         * @description Return the conversation history ordered by position; 404 when unknown/cross-tenant (Req 8.3, 4.3).
         */
        get: operations["get_conversation_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Append Message
         * @description Append a message with the next ordinal, auto-creating an unknown id (Req 8.2, 8.4).
         */
        post: operations["append_message_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description Return a summary of the caller's org documents (Req 4.2).
         */
        get: operations["list_documents_documents_get"];
        put?: never;
        /**
         * Ingest Document
         * @description Ingest an uploaded document into the caller's org and return its summary (Req 7.3).
         */
        post: operations["ingest_document_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Document
         * @description Delete the caller's org document and cascade to its chunks and embeddings.
         *
         *     A document owned by another tenant is indistinguishable from a missing one — the
         *     org-scoped ``get_document`` returns ``None`` and the caller receives ``404`` (Req 4.3).
         */
        delete: operations["delete_document_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Datasets
         * @description List the caller org's datasets; never cross-org (Req 6.5, 6.8).
         */
        get: operations["list_datasets_evaluations_datasets_get"];
        put?: never;
        /**
         * Create Dataset
         * @description Create an org-scoped Evaluation_Dataset and persist its items (Req 6.1).
         */
        post: operations["create_dataset_evaluations_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Run
         * @description Execute a run over the org-scoped dataset with named evaluators (Req 6.2, 6.5, 6.9).
         *
         *     The framework loads the dataset scoped to ``principal.org_id`` (an absent or
         *     cross-tenant dataset raises ``404 not_found``), scores every item with each named
         *     evaluator on the keyless pipeline, and persists the run; the aggregate equals the
         *     mean of the per-item scores by construction (Req 6.4, 6.9).
         */
        post: operations["create_run_evaluations_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Return a persisted run's aggregate + per-item scores; 404 if absent (Req 6.8, 6.9).
         */
        get: operations["get_run_evaluations_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guardrails/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Guardrail Config
         * @description Return the ordered active guardrails (stable ``name`` + ``kind``) (Req 5.1).
         *
         *     ``kind`` is the guardrail's implementation type name; the ordering mirrors the
         *     pipeline's stable configured evaluation order.
         */
        get: operations["get_guardrail_config_guardrails_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guardrails/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate Guardrails
         * @description Run ``content`` through the pipeline and return allow / flag / block (Req 5.2-5.5).
         */
        post: operations["evaluate_guardrails_guardrails_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Liveness: always 200 if the process is running.
         */
        get: operations["liveness_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Readiness: verify Postgres + Redis; 200 all-up, else 503 listing down deps.
         */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Integration Status
         * @description Return each integration's ``{name, enabled}`` status for the caller (Req 9.1, 9.5).
         *
         *     Enablement is derived at request time from ``Settings.integration_enabled`` — a pure
         *     function of the configured Credential presence and Enable_Setting — so the response
         *     reflects current configuration and contains only ``{name, enabled}`` pairs, never a
         *     credential (Req 9.2). Authorization is enforced entirely by the declared
         *     ``require_permission(Permission.READ)`` dependency (Req 9.3, 9.4).
         */
        get: operations["get_integration_status_integrations_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/multi-agent/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Multi Agent Run
         * @description Start a Multi_Agent_Run, persist it, and run it synchronously to completion.
         *
         *     Under the keyless auto-approve default the orchestrator terminates on the same
         *     request; streaming is exposed separately by :func:`stream_multi_agent_run`. The run
         *     is persisted before the orchestrator runs (Req 10.1), the terminal ``Final_Output``
         *     and ``Termination_Reason`` are persisted on completion (Req 10.5), and a start-time
         *     failure surfaces through the existing uniform error envelope (Req 9.1).
         *
         *     The input guardrail pipeline runs **before** the run is created and the orchestrator
         *     is invoked: a blocking guardrail raises ``AppError("guardrail_blocked", 400)`` and the
         *     downstream multi-agent orchestrator is never reached (Req 5.4). The output pipeline
         *     runs on the terminal output and its flags are attached to the response (Req 5.5, 5.6).
         */
        post: operations["start_multi_agent_run_multi_agent_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/multi-agent/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Multi Agent Run
         * @description Return the ordered trace + result for a Multi_Agent_Run (Req 9.4).
         *
         *     Unknown or cross-tenant ``run_id`` -> 404 via the envelope (Req 9.6, 4.3). When the
         *     run has terminated but its ``Final_Output`` and ``Termination_Reason`` cannot be
         *     retrieved together, a ``unavailable`` error is returned via the envelope (Req 9.5).
         */
        get: operations["get_multi_agent_run_multi_agent_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/multi-agent/runs/{run_id}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Approval
         * @description Forward an ``Approval_Decision`` to the ``Human_Approval_Gate`` (Req 9.3).
         *
         *     * Unknown ``run_id`` -> ``404 not_found`` via the envelope (Req 9.6).
         *     * A decision to a run that is not currently awaiting approval is rejected with a
         *       ``409 run-not-awaiting-approval`` error via the envelope, and the rejected attempt
         *       has already been recorded in the trace by the gate (Req 5.5).
         */
        post: operations["submit_approval_multi_agent_runs__run_id__approval_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/multi-agent/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream Multi Agent Run
         * @description Stream a fresh multi-agent run for ``run_id`` over Server-Sent Events (Req 9.2).
         *
         *     The run's ``task`` is resolved from the caller's org run store; unknown or
         *     cross-tenant id -> 404 via the envelope. The stream ends in exactly one terminal
         *     event (``completion`` or ``error``) as guaranteed by :class:`Multi_Agent_Streaming_Service`.
         */
        post: operations["stream_multi_agent_run_multi_agent_runs__run_id__stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Org
         * @description Create a NEW Organization owned by the caller (Req 2.1, 2.2).
         *
         *     Any authenticated principal may create an org; a User principal is added as its
         *     ``OWNER`` so they can immediately manage it.
         */
        post: operations["create_org_orgs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{org_id}/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Api Keys
         * @description Return metadata for every API key in ``org_id`` — never a hash or secret (Req 5.4).
         */
        get: operations["list_api_keys_orgs__org_id__api_keys_get"];
        put?: never;
        /**
         * Create Api Key
         * @description Issue an org-scoped API key; return the plaintext secret **once** (Req 5.1, 5.2).
         */
        post: operations["create_api_key_orgs__org_id__api_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{org_id}/api-keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke Api Key
         * @description Revoke an API key; an unknown or cross-org key is a 404 (Req 5.5, 5.7).
         */
        delete: operations["revoke_api_key_orgs__org_id__api_keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{org_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Member
         * @description Add an existing user (by email) to ``org_id`` under a Role (Req 2.2).
         */
        post: operations["add_member_orgs__org_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{org_id}/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Team
         * @description Create an org-scoped Team within ``org_id`` (Req 2.3).
         */
        post: operations["create_team_orgs__org_id__teams_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{org_id}/teams/{team_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Team Member
         * @description Add a user (by email) to a Team (Req 2.4, 2.5).
         *
         *     A user holding no Membership in the team's Organization propagates
         *     ``AppError("org_mismatch", 400)`` from the Identity_Store.
         */
        post: operations["add_team_member_orgs__org_id__teams__team_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Prompts
         * @description List the caller org's template names (ascending); never cross-org (Req 4.8).
         */
        get: operations["list_prompts_prompts_get"];
        put?: never;
        /**
         * Create Prompt Version
         * @description Append a new immutable Prompt_Version numbered ``max+1``/``1`` (Req 4.1, 4.9).
         */
        post: operations["create_prompt_version_prompts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prompts/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Prompt
         * @description Return the latest version, or ``?version=N``; 404 if absent (Req 4.3, 4.4, 4.8).
         */
        get: operations["get_prompt_prompts__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prompts/{name}/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render Prompt
         * @description Render a resolved version with supplied values; missing variable → 400 (Req 4.6, 4.7).
         *
         *     Resolves the version (latest or ``payload.version``) org-scoped — an absent template
         *     or cross-tenant lookup raises ``404 not_found`` — then substitutes every declared
         *     variable, raising ``400 missing_variable`` (listing the missing names) when any is
         *     omitted.
         */
        post: operations["render_prompt_prompts__name__render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prompts/{name}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Prompt Versions
         * @description Return the ascending version numbers for ``(org, name)`` (Req 4.5).
         */
        get: operations["list_prompt_versions_prompts__name__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query
         * @description Answer a query with grounding and citations, scoped to the caller's org.
         *
         *     The input guardrail pipeline runs **before** the RAG_Service is invoked: a blocking
         *     guardrail raises ``AppError("guardrail_blocked", 400)`` and the downstream generation
         *     is never reached (Req 5.4). The output pipeline then runs on the produced answer and
         *     its flags are attached to the response without blocking (Req 5.5, 5.6).
         */
        post: operations["query_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AddMemberRequest
         * @description Body for ``POST /orgs/{id}/members`` — add an existing user under a Role (Req 2.2).
         */
        AddMemberRequest: {
            /** Email */
            email: string;
            role: components["schemas"]["Role"];
        };
        /**
         * AddMemberResponse
         * @description Response describing the persisted Membership (Req 2.2).
         */
        AddMemberResponse: {
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            role: components["schemas"]["Role"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * AddTeamMemberRequest
         * @description Body for ``POST /orgs/{id}/teams/{tid}/members`` — add a user by email (Req 2.4).
         */
        AddTeamMemberRequest: {
            /** Email */
            email: string;
        };
        /**
         * AddTeamMemberResponse
         * @description Response describing the persisted Team_Membership (Req 2.4).
         */
        AddTeamMemberResponse: {
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** AgentRunRequest */
        AgentRunRequest: {
            /** Conversation Id */
            conversation_id?: string | null;
            /** Message */
            message: string;
        };
        /** AgentRunResponse */
        AgentRunResponse: {
            /** Answer */
            answer: string;
            /** Citations */
            citations?: components["schemas"]["CitationModel"][];
            /** Conversation Id */
            conversation_id: string;
            /** Flags */
            flags?: string[];
            /** Run Id */
            run_id: string;
            /**
             * Termination Reason
             * @enum {string}
             */
            termination_reason: "final-answer" | "iteration-limit-reached";
        };
        /**
         * ApiKeyMetadata
         * @description Safe API-key metadata — never the ``key_hash`` or the plaintext secret (Req 5.4).
         */
        ApiKeyMetadata: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key Prefix */
            key_prefix: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /** Revoked At */
            revoked_at?: string | null;
            role: components["schemas"]["Role"];
        };
        /** AppendMessageRequest */
        AppendMessageRequest: {
            /** Content */
            content: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "tool" | "system";
        };
        /**
         * ApprovalDecisionRequest
         * @description Body for :func:`submit_approval` — a human decision on a paused run (Req 9.3).
         */
        ApprovalDecisionRequest: {
            /** Edited Content */
            edited_content?: string | null;
            /** Feedback */
            feedback?: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "approve" | "reject" | "edit";
        };
        /**
         * ApprovalDecisionResponse
         * @description Response after applying an Approval_Decision to a paused run (Req 9.3).
         */
        ApprovalDecisionResponse: {
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "awaiting_approval" | "terminated";
            /** Termination Reason */
            termination_reason?: ("completed" | "max-rounds-reached" | "max-revisions-reached" | "rejected" | "aborted") | null;
        };
        /** Body_ingest_document_documents_post */
        Body_ingest_document_documents_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Filename */
            filename?: string | null;
        };
        /** CitationModel */
        CitationModel: {
            /** Chunk Id */
            chunk_id: string;
            /** Document Id */
            document_id: string;
        };
        /** ConversationHistoryResponse */
        ConversationHistoryResponse: {
            /** Conversation Id */
            conversation_id: string;
            /** Messages */
            messages?: components["schemas"]["MessageModel"][];
        };
        /**
         * CreateApiKeyRequest
         * @description Body for ``POST /orgs/{id}/api-keys`` — issue a key granting ``role`` (Req 5.1).
         */
        CreateApiKeyRequest: {
            role: components["schemas"]["Role"];
        };
        /**
         * CreateApiKeyResponse
         * @description Creation response carrying the plaintext secret **exactly once** (Req 5.1, 5.2).
         */
        CreateApiKeyResponse: {
            /**
             * Api Key Id
             * Format: uuid
             */
            api_key_id: string;
            /** Key Prefix */
            key_prefix: string;
            role: components["schemas"]["Role"];
            /** Secret */
            secret: string;
        };
        /** CreateConversationResponse */
        CreateConversationResponse: {
            /** Conversation Id */
            conversation_id: string;
        };
        /**
         * CreateDatasetRequest
         * @description Body for ``POST /evaluations/datasets`` — a named dataset + its items (Req 6.1).
         */
        CreateDatasetRequest: {
            /** Items */
            items?: components["schemas"]["EvaluationItemRequest"][];
            /** Name */
            name: string;
        };
        /**
         * CreateDatasetResponse
         * @description Response carrying the newly-created Evaluation_Dataset id (Req 6.1).
         */
        CreateDatasetResponse: {
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /** Name */
            name: string;
        };
        /**
         * CreateOrgRequest
         * @description Body for ``POST /orgs`` — an authenticated user creates an org they own.
         */
        CreateOrgRequest: {
            /** Name */
            name: string;
        };
        /**
         * CreateOrgResponse
         * @description Response carrying the newly-created Org_Id (Req 2.1).
         */
        CreateOrgResponse: {
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
        };
        /**
         * CreatePromptVersionRequest
         * @description Body for ``POST /prompts`` — append a new immutable Prompt_Version (Req 4.1).
         */
        CreatePromptVersionRequest: {
            /** Body */
            body: string;
            /** Name */
            name: string;
            /** Variables */
            variables?: string[];
        };
        /**
         * CreateTeamRequest
         * @description Body for ``POST /orgs/{id}/teams`` — create an org-scoped Team (Req 2.3).
         */
        CreateTeamRequest: {
            /** Name */
            name: string;
        };
        /**
         * CreateTeamResponse
         * @description Response carrying the newly-created Team id (Req 2.3).
         */
        CreateTeamResponse: {
            /** Name */
            name: string;
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
        };
        /**
         * DatasetSummary
         * @description Safe metadata for one Evaluation_Dataset in the org's list (Req 6.5).
         */
        DatasetSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /** Name */
            name: string;
        };
        /** DocumentSummary */
        DocumentSummary: {
            /** Chunk Count */
            chunk_count: number;
            /** Content Type */
            content_type: string;
            /** Created At */
            created_at: string;
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /** Size Bytes */
            size_bytes: number;
            /** Status */
            status: string;
        };
        /**
         * EvaluationItemRequest
         * @description One dataset item: an input and an optional expected output (Req 6.1).
         */
        EvaluationItemRequest: {
            /** Expected */
            expected?: string | null;
            /** Input */
            input: string;
        };
        /**
         * EvaluationItemScore
         * @description The score one Evaluator assigned to one item within a run (Req 6.9).
         */
        EvaluationItemScore: {
            /** Evaluator */
            evaluator: string;
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            /** Score */
            score: number;
        };
        /**
         * EvaluationRunRequest
         * @description Body for ``POST /evaluations/runs`` — run named evaluators over a dataset (Req 6.2).
         */
        EvaluationRunRequest: {
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /** Evaluators */
            evaluators: string[];
        };
        /**
         * EvaluationRunResponse
         * @description A persisted Evaluation_Run: aggregate + per-item scores (Req 6.9).
         */
        EvaluationRunResponse: {
            /** Aggregate Score */
            aggregate_score: number;
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /** Results */
            results?: components["schemas"]["EvaluationItemScore"][];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /**
         * FinalOutputModel
         * @description The Final_Output emitted when a Multi_Agent_Run terminates successfully.
         */
        FinalOutputModel: {
            /** Citations */
            citations?: components["schemas"]["CitationModel"][];
            /** Content */
            content: string;
        };
        /**
         * GuardrailConfigResponse
         * @description The ordered list of active guardrails (names + kinds) (Req 5.1).
         */
        GuardrailConfigResponse: {
            /** Guardrails */
            guardrails?: components["schemas"]["GuardrailInfo"][];
        };
        /**
         * GuardrailEvaluateRequest
         * @description Body for ``POST /guardrails/evaluate`` — content to run through the pipeline.
         */
        GuardrailEvaluateRequest: {
            /**
             * Content
             * @default
             */
            content: string;
        };
        /**
         * GuardrailEvaluateResponse
         * @description The pipeline's allow / flag / block decision with flags/reason (Req 5.2-5.5).
         */
        GuardrailEvaluateResponse: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "allow" | "flag" | "block";
            /** Flags */
            flags?: string[];
            /** Reason */
            reason?: string | null;
        };
        /**
         * GuardrailInfo
         * @description An active guardrail's stable name and kind (Req 5.1).
         */
        GuardrailInfo: {
            /** Kind */
            kind: string;
            /** Name */
            name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestResponse */
        IngestResponse: {
            /** Chunk Count */
            chunk_count: number;
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /**
             * Status
             * @constant
             */
            status: "ingested";
        };
        /**
         * IntegrationStatusEntry
         * @description One integration's public status: its stable name and whether it is Enabled.
         *
         *     Contains only ``{name, enabled}`` — never a credential, token, or secret-derived
         *     field (Req 9.2, 9.5).
         */
        IntegrationStatusEntry: {
            /** Enabled */
            enabled: boolean;
            /** Name */
            name: string;
        };
        /**
         * IntegrationStatusResponse
         * @description The org-scoped Integration_Status view: one ``{name, enabled}`` entry per integration.
         *
         *     No credential, token, or secret-derived field appears anywhere in the response (Req 9.2).
         */
        IntegrationStatusResponse: {
            /** Integrations */
            integrations?: components["schemas"]["IntegrationStatusEntry"][];
        };
        /** LivenessResponse */
        LivenessResponse: {
            /**
             * Status
             * @default alive
             * @constant
             */
            status: "alive";
        };
        /**
         * LoginRequest
         * @description Login body: verifies credentials to issue an Access_Token (Req 1.2, 1.3).
         */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MessageModel */
        MessageModel: {
            /** Content */
            content: string;
            /** Position */
            position: number;
            /** Role */
            role: string;
        };
        /**
         * MultiAgentRunResult
         * @description Full run result: status, termination reason, final output, and trace (Req 9.4).
         */
        MultiAgentRunResult: {
            final_output?: components["schemas"]["FinalOutputModel"] | null;
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "awaiting_approval" | "terminated";
            /** Termination Reason */
            termination_reason?: ("completed" | "max-rounds-reached" | "max-revisions-reached" | "rejected" | "aborted") | null;
            /** Trace */
            trace?: components["schemas"]["TraceEntryModel"][];
        };
        /**
         * PromptVersionResponse
         * @description A resolved Prompt_Version (latest or a specific number) (Req 4.3, 4.4).
         */
        PromptVersionResponse: {
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Variables */
            variables?: string[];
            /** Version */
            version: number;
        };
        /** QueryRequest */
        QueryRequest: {
            /** Query */
            query: string;
            /** Top K */
            top_k?: number | null;
        };
        /** QueryResponse */
        QueryResponse: {
            /** Answer */
            answer: string;
            /** Citations */
            citations?: components["schemas"]["CitationModel"][];
            /** Flags */
            flags?: string[];
            /** Grounded */
            grounded: boolean;
            /** Provider */
            provider: string;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Dependencies */
            dependencies: {
                [key: string]: "up" | "down";
            };
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
        };
        /**
         * RegisterSelfRequest
         * @description Self-registration body: bootstraps a new Organization + owner User (Req 1.1).
         */
        RegisterSelfRequest: {
            /** Email */
            email: string;
            /** Org Name */
            org_name: string;
            /** Password */
            password: string;
        };
        /**
         * RenderPromptRequest
         * @description Body for ``POST /prompts/{name}/render`` — supply the variable values (Req 4.6).
         */
        RenderPromptRequest: {
            /** Variables */
            variables?: {
                [key: string]: string;
            };
            /** Version */
            version?: number | null;
        };
        /**
         * RenderPromptResponse
         * @description The rendered prompt string for a resolved version (Req 4.6).
         */
        RenderPromptResponse: {
            /** Name */
            name: string;
            /** Rendered */
            rendered: string;
            /** Version */
            version: number;
        };
        /**
         * Role
         * @description A named set of Permissions assigned to a Membership or API_Key.
         * @enum {string}
         */
        Role: "owner" | "admin" | "member" | "viewer";
        /**
         * StartMultiAgentRunRequest
         * @description Request body for starting a Multi_Agent_Run (Req 9.1).
         */
        StartMultiAgentRunRequest: {
            /** Conversation Id */
            conversation_id?: string | null;
            /** Task */
            task: string;
        };
        /**
         * StartMultiAgentRunResponse
         * @description Response for :class:`StartMultiAgentRunRequest` (Req 9.1).
         */
        StartMultiAgentRunResponse: {
            /** Conversation Id */
            conversation_id: string;
            /** Flags */
            flags?: string[];
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "awaiting_approval" | "terminated";
        };
        /**
         * TokenResponse
         * @description A freshly-issued bearer Access_Token (Req 1.2).
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /** TraceEntryModel */
        TraceEntryModel: {
            /** Ordinal */
            ordinal: number;
            /** Outcome */
            outcome?: string | null;
            /** Role Id */
            role_id?: string | null;
            /** Step Type */
            step_type: string;
            /** Tool Name */
            tool_name?: string | null;
        };
        /** TraceResponse */
        TraceResponse: {
            /** Entries */
            entries?: components["schemas"]["TraceEntryModel"][];
            /** Run Id */
            run_id: string;
        };
        /**
         * UsageBreakdownEntry
         * @description One grouped row of a usage breakdown (by provider / model / user) (Req 3.2).
         */
        UsageBreakdownEntry: {
            /** Key */
            key: string;
            /** Total Cost */
            total_cost: string;
            /** Total Tokens */
            total_tokens: number;
        };
        /**
         * UsageReportResponse
         * @description Aggregated usage + cost for the caller's org over a time range (Req 3.1, 3.4).
         */
        UsageReportResponse: {
            /** By Model */
            by_model?: components["schemas"]["UsageBreakdownEntry"][];
            /** By Provider */
            by_provider?: components["schemas"]["UsageBreakdownEntry"][];
            /** By User */
            by_user?: components["schemas"]["UsageBreakdownEntry"][];
            /**
             * End
             * Format: date-time
             */
            end: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Total Cost */
            total_cost: string;
            /** Total Tokens */
            total_tokens: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    run_agent_agent_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_trace_agent_runs__run_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_agent_agent_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_usage_analytics_usage_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    register_self_auth_register_self_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterSelfRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateConversationResponse"];
                };
            };
        };
    };
    get_conversation_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    append_message_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppendMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSummary"][];
                };
            };
        };
    };
    ingest_document_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_document_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_evaluations_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSummary"][];
                };
            };
        };
    };
    create_dataset_evaluations_datasets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDatasetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateDatasetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_evaluations_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluationRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_evaluations_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_guardrail_config_guardrails_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuardrailConfigResponse"];
                };
            };
        };
    };
    evaluate_guardrails_guardrails_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuardrailEvaluateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuardrailEvaluateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    liveness_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    get_integration_status_integrations_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationStatusResponse"];
                };
            };
        };
    };
    start_multi_agent_run_multi_agent_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartMultiAgentRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartMultiAgentRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_multi_agent_run_multi_agent_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MultiAgentRunResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_approval_multi_agent_runs__run_id__approval_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalDecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_multi_agent_run_multi_agent_runs__run_id__stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_org_orgs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrgRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateOrgResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_api_keys_orgs__org_id__api_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyMetadata"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_key_orgs__org_id__api_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApiKeyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateApiKeyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_key_orgs__org_id__api_keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_orgs__org_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddMemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_team_orgs__org_id__teams_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTeamRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTeamResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_team_member_orgs__org_id__teams__team_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                team_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddTeamMemberRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddTeamMemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_prompts_prompts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    create_prompt_version_prompts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePromptVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prompt_prompts__name__get: {
        parameters: {
            query?: {
                version?: number | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_prompt_prompts__name__render_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenderPromptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderPromptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_prompt_versions_prompts__name__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
